fun:
  stickers:
    TYST: #<sticker_id>
  hannah: #<userid>
  hannah-haters: #<role_id>
  chess_emojis:
    blunder: #<emoji_id>
    mistake: #<emoji_id>
    inaccuracy: #<emoji_id>
    excellent: #<emoji_id>
    best: #<emoji_id>
    brilliant: #<emoji_id>
  special_users:
    #<userid>:
    #- "<emoji>" OR
    #- ["<emoji1>", "<emoji2>", ...]
    #- ...

roles:
  bot_devs:
    users:
      - #<user_id>
    role: #<role_id>
  gameroom_staff:
    users:
      - #<user_id>
    role: #<role_id>
  leadership:
    role: #<role_id>
  gameheads:
    valorant: #<role_id>
    league: #<role_id>
    overwatch: #<role_id>
    smash: #<role_id>
    deadlock: #<role_id>
    cs2: #<role_id>
    rocket_league: #<role_id>
    mario_kart: #<role_id>
    rivals: #<role_id>
    rhythm_games: #<role_id>
    apex: #<role_id>

reservations:
  # where the outputs of reservations gets sent to (ie gameroom staff channel)
  channel: #<channel_id>

gameheads:
  valorant:
    #<discord_username>: "<email>"
  league:
    #<discord_username>: "<email>"
  overwatch:
    #<discord_username>: "<email>"
  smash:
    #<discord_username>: "<email>"
  deadlock:
    #<discord_username>: "<email>"
  cs2:
    #<discord_username>: "<email>"
  rocket_league:
    #<discord_username>: "<email>"
  mario_kart:
    #<discord_username>: "<email>"
  rivals:
    #<discord_username>: "<email>"
  rhythm_games:
    #<discord_username>: "<email>"
  apex:
    #<discord_username>: "<email>"

github_backlog:
  pr_channel: #<channel_id>
  issue_channel: #<channel_id>
