fun:
  hannah: #<userid>
  hannah-haters: #<role_id>
  chess_emojis:
    blunder: #<emoji_id>
    mistake: #<emoji_id>
    inaccuracy: #<emoji_id>
    excellent: #<emoji_id>
    best: #<emoji_id>
    brilliant: #<emoji_id>
  special_users:
    #<userid>:
    #- "<emoji>" OR
    #- ["<emoji1>", "<emoji2>", ...]
    #- ...

gameroom:
  staff:
  - #<user_id>
  
reservations:
  # where the outputs of reservations gets sent to (ie gameroom staff channel)
  channel: #<channel_id>
  # who can invoke the reserve command
  roles:
    - #<role_id>
    - #<role_id>
    # - ...

gameheads:
  #<account_id>: "corresponding email"
  example: "example@email.com"

bot_devs:
  - #<user_id>

github_backlog:
  pr_channel: #<channel_id>
  issue_channel: #<channel_id>
