#!/usr/bin/env python3
"""Regenerates overwatch.yaml's hero_keys and hero_roles blocks from the OverFast API.

New hero dropped? Same order as League's champions:
  1. drop the image in assets/games/overwatch/characters/<name>.webp
  2. add the name to the characters list in overwatch.yaml
  3. run this (python scripts/update_overwatch_heroes.py) to pick up the new key/role

Only touches the hero_keys/hero_roles blocks, nothing else in the file gets touched.
"""
import json
import urllib.request
from pathlib import Path

import yaml

OVERWATCH_YAML = Path(__file__).resolve().parent.parent / "data" / "games" / "overwatch.yaml"
HEROES_URL = "https://overfast-api.tekrop.fr/heroes"
VALID_ROLES = {"tank", "damage", "support"}

KEYS_HEADER = (
    "hero_keys: # OverFast hero key -> name, for mapping career-stats results. Regenerate\n"
    "           # with scripts/update_overwatch_heroes.py when a new hero is added to the\n"
    "           # characters list above.\n"
)
ROLES_HEADER = (
    "hero_roles: # OverFast hero key -> Tank/Damage/Support, for auto-filling a player's\n"
    "            # roles from their top-3 mains. Regenerated by the same script as above.\n"
)


def fetch_json(url: str) -> list:
    req = urllib.request.Request(url, headers={"User-Agent": "nu-esports-bot/update-script"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.load(resp)


def main() -> None:
    heroes = fetch_json(HEROES_URL)
    entries = sorted(((h["name"], h["key"]) for h in heroes), key=lambda item: item[0].lower())

    text = OVERWATCH_YAML.read_text(encoding="utf-8")
    parsed = yaml.safe_load(text)
    yaml_characters = set(parsed.get("characters") or [])
    api_names = {name for name, _ in entries}

    missing_from_yaml = api_names - yaml_characters
    extra_in_yaml = yaml_characters - api_names
    if missing_from_yaml:
        print(f"heads up: {len(missing_from_yaml)} hero(es) in OverFast but not in `characters:` yet, "
              "add them there too + drop an image in assets/games/overwatch/characters/:")
        for name in sorted(missing_from_yaml):
            print(f"  - {name}")
    if extra_in_yaml:
        print(f"heads up: {len(extra_in_yaml)} name(s) in `characters:` that OverFast doesn't know about "
              "(typo? hero renamed?):")
        for name in sorted(extra_in_yaml):
            print(f"  - {name}")

    for h in heroes:
        if h["role"] not in VALID_ROLES:
            print(f"heads up: {h['name']} has an unrecognized role \"{h['role']}\" -- skipping it in hero_roles")

    # yaml treats ": " inside an unquoted scalar as another mapping -- Soldier: 76 needs
    # quoting or this breaks
    keys_body = "\n".join(f"  {key}: '{name}'" if ":" in name else f"  {key}: {name}" for name, key in entries)
    keys_block = KEYS_HEADER + keys_body + "\n"

    role_entries = sorted(
        ((h["key"], h["role"].title()) for h in heroes if h["role"] in VALID_ROLES),
        key=lambda item: item[0],
    )
    roles_body = "\n".join(f"  {key}: {role}" for key, role in role_entries)
    roles_block = ROLES_HEADER + roles_body + "\n"

    marker = "hero_keys:" if "hero_keys:" in text else None
    before = text[: text.index(marker)].rstrip("\n") + "\n\n" if marker else text.rstrip("\n") + "\n\n"

    OVERWATCH_YAML.write_text(before + keys_block + "\n" + roles_block, encoding="utf-8")
    print(f"wrote {len(entries)} hero_keys and {len(role_entries)} hero_roles entries to {OVERWATCH_YAML}")


if __name__ == "__main__":
    main()
